// users
export const FETCH_USERS = 'FETCH_USERS'
export const ADD_USER_TO_SELECTED_USERS_LIST = 'ADD_USER_TO_SELECTED_USERS_LIST'
export const REMOVE_USER_FROM_SELECTED_USERS_LIST = 'REMOVE_USER_FROM_SELECTED_USERS_LIST'
export const ADD_USER_TO_USERS_LIST = 'ADD_USER_TO_USERS_LIST'
export const REMOVE_USER_FROM_USERS_LIST = 'REMOVE_USER_FROM_USERS_LIST'
export const CLEAR_USERS_LIST = 'CLEAR_USERS_LIST'
export const CLEAR_SELECTED_USERS_LIST = 'CLEAR_SELECTED_USERS_LIST'

// user
export const SET_USER = 'SET_USER'
export const CLEAR_USER = 'CLEAR_USER'

// auth
export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
